version: "3.8"

services:
  flask:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - redis
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
       - redis-data:/data

volumes:
   redis-data:
